# Generated by Django 6.0.7 on 2026-07-15 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('role', models.CharField(choices=[('policyholder', 'Policyholder'), ('staff', 'Insurance Staff'), ('investigator', 'Investigator'), ('administrator', 'Administrator')], default='policyholder', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('disabled', 'Disabled'), ('archived', 'Archived')], default='active', max_length=20)),
                ('employee_number', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, choices=[('claims', 'Claims'), ('underwriting', 'Underwriting'), ('customer_support', 'Customer Support'), ('policy_admin', 'Policy Administration'), ('finance', 'Finance'), ('compliance', 'Compliance'), ('it', 'IT'), ('hr', 'Human Resources'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('fraud_investigation', 'Fraud Investigation'), ('forensic_investigation', 'Forensic Investigation'), ('special_investigations', 'Special Investigations'), ('claims_investigation', 'Claims Investigation')], max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('specialization', models.CharField(blank=True, choices=[('vehicle_fraud', 'Vehicle Fraud'), ('property_fraud', 'Property Fraud'), ('health_fraud', 'Health Fraud'), ('life_fraud', 'Life Insurance Fraud'), ('cyber_fraud', 'Cyber Fraud'), ('general_fraud', 'General Fraud'), ('organized_crime', 'Organized Crime')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_trust_score', models.IntegerField(default=100)),
                ('fraud_risk_level', models.CharField(default='Low', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
