# Generated by Django 6.0.7 on 2026-07-16 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_invited_by_userprofile_is_verified_and_more'),
    ]

    operations = [
    ]
